name: CI/CD Pipeline

on:
  push:
    branches: 
      - main
      - develop
  workflow_dispatch:

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write       
      packages: write       
      issues: write         
      pull-requests: write  
    
    outputs:
      published: ${{ steps.semantic.outputs.new_release_published }}
      version: ${{ steps.semantic.outputs.new_release_version }}
      docker_alias: ${{ steps.vars.outputs.docker_alias }}
      owner_lower: ${{ steps.vars.outputs.owner_lower }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Run Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v4
      with:
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine Docker Alias & Lowercase Owner
      if: steps.semantic.outputs.new_release_published == 'true'
      id: vars
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "docker_alias=latest" >> $GITHUB_OUTPUT
        else
          echo "docker_alias=dev" >> $GITHUB_OUTPUT
        fi
        
        OWNER_LOWER="${GITHUB_REPOSITORY_OWNER,,}"
        echo "owner_lower=$OWNER_LOWER" >> $GITHUB_OUTPUT

  build-and-pack:
    runs-on: ubuntu-latest
    needs: releas
    if: needs.release.outputs.published == 'true'

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore Local Tools
      run: dotnet tool restore
      
    - name: Build DROWeb.WebAPI & UnitySDK
      run: |
        dotnet build DROWeb.WebAPI/DROWeb.WebAPI.csproj -c Release
        dotnet nswag openapi2csclient /input:"DROWeb.WebAPI/obj/openapi/DROWeb.WebAPI.json" /output:"DROWeb.UnitySDK/DROWebApiClient.cs" /namespace:DROWeb.UnitySDK /jsonLibrary:NewtonsoftJson /generateDataAnnotations:false
        dotnet build DROWeb.UnitySDK/DROWeb.UnitySDK.csproj -c Release -o DROWeb.UnitySDK/Runtime/

    - name: Generate UnitySDK metafiles
      uses: rouvydev/metagen-gha@v1.4
      with:
        seed: 'random-seed'
        directory: 'DROWeb.UnitySDK'
        
    - name: Publish UPM Package
      run: |
        cd DROWeb.UnitySDK
        sed -i "s/\"version\": \".*\"/\"version\": \"${{ needs.release.outputs.version }}\"/g" package.json
        echo "//${{ vars.REGISTRY_HOST }}/:_authToken=${{ secrets.VERDACCIO_TOKEN }}" > .npmrc
        npm publish --registry=https://${{ vars.REGISTRY_HOST }}/
        
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./DROWeb.WebAPI/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ needs.release.outputs.owner_lower }}/droweb-backend:${{ needs.release.outputs.version }}
          ghcr.io/${{ needs.release.outputs.owner_lower }}/droweb-backend:${{ needs.release.outputs.docker_alias }}